### ISSUE TITLE
Applications Menu List element visual disalignment

### ISSUE THREAD

**Issue by Type-32** [SmartSheep-Studio/NetGlue#6]
One part of the line in the list is segmented due to slight vertical displacement
<img width="1300" alt="Screenshot 2023-01-23 at 19 42 36" src="https://user-images.githubusercontent.com/87076491/214031622-996562df-dec2-4681-bc46-895f8664bf32.png">

**Comment by LittleSheep2Code** [comment]
I think that is your browser question, please use last version chrome, microsoft edge or firefox or remove some plugins. Because it work good for me and my computer.
