### ISSUE TITLE
"Lockdown" Button Dysfunctional

### ISSUE THREAD

**Issue by Type-32** [SmartSheep-Studio/NetGlue#7]
The "Lockdown" button in the Applications menu does not react on click.
<img width="587" alt="Screenshot 2023-01-23 at 19 48 28" src="https://user-images.githubusercontent.com/87076491/214032418-87e28f1f-260f-4426-9f14-aa8cc6e0fc87.png">

**Comment by LittleSheep2Code** [comment]
This button just a blank because I do not any idea to use that empty space(LOL
I will fix~~remove~~ that on next version
