### ISSUE TITLE
[Bug] Axios Request Failure Error Code 500 when Saving New Collection Data

### ISSUE THREAD

**Issue by Type-32** [SmartSheep-Studio/NetGlue#9]
![image](https://user-images.githubusercontent.com/87076491/215034743-ebea9e66-f1cd-439d-ad67-78747aa7897a.png)

**Comment by Type-32** [comment]
Only happens when "Enable File Storage Pool" option is disabled

**Comment by LittleSheep2Code** [comment]
Please open your inspect and switch to Network Tab put the request response to here pls
